development:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_SUBSCRIPTIONS_URL'] || 'mongodb://localhost:27017/subscriptions_development' %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] || 'mongodb://localhost:27017/people_development' %>
test:
  sessions:
    default:
      database: subscriptions_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    # set opptions
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_SUBSCRIPTIONS_URL'] %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] %>
